<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('questions')->insert([
            [
                'question' => '<p>Trong các câu sau, câu nào là mệnh đề?</p>',
                'correct_answer' => '1',
                'answer_a' => '<p>Trung Quốc là nước đông dân nhất thế giới.</p>',
                'answer_b' => '<p>Bạn học trường nào?</p>',
                'answer_c' => '<p>Đi ngủ đi!</p>',
                'answer_d' => '<p>Không được làm việc riêng trong giờ học.</p>',
                'image' => NULL,
                'explain' => '<p>Chỉ có câu “Trung Quốc là nước đông dân nhất thế giới” có thể xác định được tính đúng sai nên đáp án B là mệnh đề.</p>',
                'level' => 1,
                'teacher_id' => NULL,
                'subject_id' => 1,
                'shared' => 1,
            ],
            [
                'question' => '<p>Trong các câu sau, câu nào <strong>không</strong> phải là mệnh đề?</p>',
                'correct_answer' => '1',
                'answer_a' => '<p>Buồn ngủ quá!</p>',
                'answer_b' => '<p>Hình thoi có hai đường chéo vuông góc với nhau</p>',
                'answer_c' => '<p>8 là số chính phương</p>',
                'answer_d' => '<p>Băng Cốc là thủ đô của Mianma.</p>',
                'image' => NULL,
                'explain' => '<p>“Buồn ngủ quá!” là câu cảm thán không xác định được tính đúng sai. Do đó không phải là mệnh đề.</p>',
                'level' => 1,
                'teacher_id' => NULL,
                'subject_id' => 1,
                'shared' => 1,
            ],
            [
                'question' => '<p>Câu nào sau đây <strong>không</strong> là mệnh đề?</p>',
                'correct_answer' => '1',
                'answer_a' => '<p>x > 2;</p>',
                'answer_b' => '<p>3 < 1;</p>',
                'answer_c' => '<p>4 – 5 = 1;</p>',
                'answer_d' => '<p>Tam giác đều là tam giác có ba cạnh bằng nhau.</p>',
                'image' => NULL,
                'explain' => '<p>Vì x > 2 là mệnh đề chứa biến không xác định được tính đúng sai nên không phải mệnh đề.</p>',
                'level' => 1,
                'teacher_id' => NULL,
                'subject_id' => 1,
                'shared' => 1,
            ],
            [
                'question' => '<p>Số tập con của tập A = {1; 2; 3} là</p>',
                'correct_answer' => '4',
                'answer_a' => '<p>5</p>',
                'answer_b' => '<p>6</p>',
                'answer_c' => '<p>7</p>',
                'answer_d' => '<p>8</p>',
                'image' => NULL,
                'explain' => '<p>Các tập con gồm {1}; {2}; {3}; {1; 2}; {1;3}; {2; 3}; {1; 2; 3}; ∅.</p>',
                'level' => 1,
                'teacher_id' => 1,
                'subject_id' => 1,
                'shared' => 1,
            ],
            [
                'question' => '<p>Số tập con có 2 phần tử của tập M = {1; 2; 3; 4; 5; 6}</p>',
                'correct_answer' => '2',
                'answer_a' => '<p>14</p>',
                'answer_b' => '<p>15</p>',
                'answer_c' => '<p>16</p>',
                'answer_d' => '<p>17</p>',
                'image' => NULL,
                'explain' => '<p>Tập con có 2 phần tử của tập M gồm: {1; 2}; {1; 3}; {1; 4}; {1; 5}; {1;6}; {2; 3}; {2; 4}; {2; 5}; {2; 6}; {3; 4}; {3; 5}; {3; 6}; {4; 5}; {4; 6}; {5; 6}.<br>Vậy tập M có 15 tập con có 2 phần tử.</p>',
                'level' => 1,
                'teacher_id' => 1,
                'subject_id' => 1,
                'shared' => 1,
            ],
            [
                'question' => '<p>Trong các câu sau, có bao nhiêu câu là mệnh đề?<br>a) Hãy đi nhanh lên!<br>b) Hà Nội là thủ đô của Việt Nam.<br>c) 4 + 5 + 7 = 15.<br>d) Năm 2018 là năm nhuận.</p>',
                'correct_answer' => '3',
                'answer_a' => '<p>1</p>',
                'answer_b' => '<p>2</p>',
                'answer_c' => '<p>3</p>',
                'answer_d' => '<p>4</p>',
                'image' => NULL,
                'explain' => '<p>Câu a) là câu cảm thán không xác định được tính đúng, sai nên câu a không phải là mệnh đề.<br>Các câu b), c), d) đều có thể xác định được tính đúng sai. Do đó các câu b), c), d) đều là mệnh đề.<br>Vậy có tất cả 3 mệnh đề</p>',
                'level' => 2,
                'teacher_id' => 1,
                'subject_id' => 1,
                'shared' => 1,
            ],
            [
                'question' => '<p>Cho hai tập hợp A = {0; 2; 3; 5} và B = {2; 7}. Khi đó A ∩ B</p>',
                'correct_answer' => '2',
                'answer_a' => '<p>{2; 5}</p>',
                'answer_b' => '<p>{2}</p>',
                'answer_c' => '<p>∅</p>',
                'answer_d' => '<p>{0; 2; 3; 5; 7}</p>',
                'image' => NULL,
                'explain' => '<p>Vì phần tử 2 vừa thuộc A vừa thuộc B nên A ∩ B = (2)</p>',
                'level' => 1,
                'teacher_id' => 1,
                'subject_id' => 1,
                'shared' => 0,
            ],
            [
                'question' => '<p>Một lớp học có 16 học sinh học giỏi môn Toán; 12 học sinh học giỏi môn Văn; 8 học sinh vừa học giỏi môn Toán và Văn; 19 học sinh không học giỏi cả hai môn Toán và Văn. Hỏi lớp học có bao nhiêu học sinh?</p>',
                'correct_answer' => '2',
                'answer_a' => '<p>31</p>',
                'answer_b' => '<p>39</p>',
                'answer_c' => '<p>47</p>',
                'answer_d' => '<p>54</p>',
                'image' => NULL,
                'explain' => '<p>Gọi A là tập hợp gồm các học sinh trong lớp; B là tập số học sinh giỏi Toán; C là tập số học sinh giỏi Văn; D là tập số học sinh không giỏi cả 2 môn Toán và Văn.<br>Khi đó n(B) = 16, n(C) = 12, n(B∩C) = 8, n(D) = 19.<br>Số học sinh trong lớp giỏi ít nhất một trong hai môn Toán hoặc Văn là:<br>n(B∪C) = n(B) + n(C) - n(B∩C) = 16 + 12 – 8 = 20.<br>Ta có A = (B ∪ C) ∪ D<br>Số học sinh trong lớp là: n(A) = n(B ∪ C) + n(D) = 20 + 19 = 39 (học sinh)</p>',
                'level' => 2,
                'teacher_id' => 1,
                'subject_id' => 1,
                'shared' => 0,
            ],
            [
                'question' => '<p>Cho A = {a; b; c}; B = {b; c; d}; C = {a; b; c; d; e}. Khẳng định nào sau đây sai</p>',
                'correct_answer' => '1',
                'answer_a' => '<p>(A ∪ B) ∩ C = (A ∩ B) ∪ C</p>',
                'answer_b' => '<p>A ∪ (B ∩ C) = (A ∪ B) ∩ (A ∪ C)</p>',
                'answer_c' => '<p>A ∪ (B ∩ C) = (A ∪ B) ∩ C</p>',
                'answer_d' => '<p>(A ∪ B) ∩ C = (A ∪ B) ∩ (A ∪ C)</p>',
                'image' => NULL,
                'explain' => NULL,
                'level' => 3,
                'teacher_id' => 2,
                'subject_id' => 1,
                'shared' => 1,
            ],
            [
                'question' => '<p>Mệnh đề ∀ x ∈ R, x<sup>2</sup> − 2 + a > 0 với a là số thực cho trước. Tìm a để mệnh đề đúng</p>',
                'correct_answer' => '4',
                'answer_a' => '<p>a ≥ 2;</p>',
                'answer_b' => '<p>a < 2;</p>',
                'answer_c' => '<p>a = 2;</p>',
                'answer_d' => '<p>a > 2.</p>',
                'image' => NULL,
                'explain' => '<p>Vì x2 ≥ 0, nên để x2 – 2 + a > 0 khi – 2 + a > 0 ⇔ a > 2.</p>',
                'level' => 2,
                'teacher_id' => 2,
                'subject_id' => 1,
                'shared' => 1,
            ],
            [
                'question' => '<p>Cho A = {a; b; m; n}; B = {b; c; m}; C = {a; m; n}. Hãy chọn khẳng định đúng.</p>',
                'correct_answer' => '1',
                'answer_a' => '<p>(A \ B) ∪ (A ∩ C) = (a; m; n);</p>',
                'answer_b' => '<p>(A \ B) ∪ (A ∩ C) = (a; c; m; n);</p>',
                'answer_c' => '<p>(A \ B) ∪ (A ∩ C) = (a; b; m; n);</p>',
                'answer_d' => '<p>(A \ B) ∪ (A ∩ C) = (a; n);</p>',
                'image' => NULL,
                'explain' => '<p>A \ B = {a; n}; A ∩ C = (a; m; n) ⇒ (A \ B) ∪ (A ∩ C) = (a; m; n)</p>',
                'level' => 2,
                'teacher_id' => 2,
                'subject_id' => 1,
                'shared' => 0,
            ],
            [
                'question' => '<p>Một lớp có 45 học sinh. Mỗi em đều đăng ký chơi ít nhất một trong hai môn: bóng đá và bóng chuyền. Có 35 em đăng ký môn bóng đá, 15 em đăng ký môn bóng chuyền. Hỏi có bao nhiêu em đăng ký chơi cả 2 môn?</p>',
                'correct_answer' => '1',
                'answer_a' => '<p>5</p>',
                'answer_b' => '<p>10</p>',
                'answer_c' => '<p>15</p>',
                'answer_d' => '<p>20</p>',
                'image' => NULL,
                'explain' => '<p>Gọi A là tập hợp các học sinh đăng ký chơi bóng đá, B là tập hợp các học sinh đăng ký chơi bóng chuyền. Dựa vào biểu đồ Ven, ta có: số học sinh đăng ký cả 2 môn là (A ∩ B) = (A) + (B) − (A ∪ B) = 35 + 15 − 45 = 5</p>',
                'level' => 2,
                'teacher_id' => 1,
                'subject_id' => 1,
                'shared' => 1,
            ],
            [
                'question' => '<p>Bất phương trình nào sau đây là bất phương trình bậc nhất hai ẩn?</p>',
                'correct_answer' => '4',
                'answer_a' => '<p>x<sup>2</sup> + y > 0;</p>',
                'answer_b' => '<p>x<sup>2</sup> + 3y<sup>2</sup> = 2;</p>',
                'answer_c' => '<p>–x + y<sup>3</sup> ≤ 0;</p>',
                'answer_d' => '<p>x – y < 1.</p>',
                'image' => NULL,
                'explain' => NULL,
                'level' => 1,
                'teacher_id' => 1,
                'subject_id' => 1,
                'shared' => 1,
            ],
            [
                'question' => '<p>Bất phương trình nào tương đương với bất phương trình 3x – y > 7(x – 4y) + 1?</p>',
                'correct_answer' => '4',
                'answer_a' => '<p>4x – 27y + 1 > 0;</p>',
                'answer_b' => '<p>4x – 27y + 1 ≥ 0;</p>',
                'answer_c' => '<p>4x – 27y  < –1;</p>',
                'answer_d' => '<p>4x – 27y + 1 ≤ 0.</p>',
                'image' => NULL,
                'explain' => '3x – y > 7(x – 4y) + 1<br>⇔ 3x – y > 7x – 28y + 1<br>⇔ 0 > 7x – 3x – 28y + y + 1<br>⇔ 4x – 27y  + 1 < 0<br> ⇔ 4x – 27y  <p –1.</p>',
                'level' => 1,
                'teacher_id' => 4,
                'subject_id' => 1,
                'shared' => 1,
            ],
            [
                'question' => '<p>Cho bất phương trình x + y ≤ 2 (1). Chọn khẳng định đúng trong các khẳng định sau:</p>',
                'correct_answer' => '3',
                'answer_a' => '<p>Bất phương trình (1) chỉ có một nghiệm duy nhất;</p>',
                'answer_b' => '<p>Bất phương trình (1) chỉ có hai nghiệm;</p>',
                'answer_c' => '<p>Bất phương trình (1) luôn có vô số nghiệm;</p>',
                'answer_d' => '<p>Bất phương trình (1) vô nghiệm.</p>',
                'image' => NULL,
                'explain' => '<p>Trên mặt phẳng tọa độ, đường thẳng d: x + y = 2 chia mặt phẳng thành hai nửa mặt phẳng.<br>Với cặp số (x; y) = (0; 0) ta có: 0 + 0 = 0 < 2. Suy ra cặp số (x; y) = (0; 0) là một nghiệm của bất phương trình x + y ≤ 2 (1).<br>Vậy miền nghiệm của bất phương trình x + y ≤ 2 là nửa mặt phẳng bờ là đường thẳng d có chứa điểm O(0;0) (kể cả d).<br>Do đó, bất phương trình (1) luôn có vô số nghiệm.<br>Vậy ta chọn phương án C.</p>',
                'level' => 2,
                'teacher_id' => 4,
                'subject_id' => 1,
                'shared' => 1,
            ],
            [
                'question' => '<p>Giá trị của tan(180°) bằng</p>',
                'correct_answer' => '2',
                'answer_a' => '<p>1</p>',
                'answer_b' => '<p>0</p>',
                'answer_c' => '<p>-1</p>',
                'answer_d' => '<p>Không xác định</p>',
                'image' => NULL,
                'explain' => NULL,
                'level' => 1,
                'teacher_id' => 4,
                'subject_id' => 1,
                'shared' => 1,
            ],
            [
                'question' => '<p>Cho 0° < α < 90°. Kết luận nào sau đây đúng</p>',
                'correct_answer' => '2',
                'answer_a' => '<p>tan(α) > 0; cot(α) > 0;</p>',
                'answer_b' => '<p>tan(α) < 0; cot(α) < 0;</p>',
                'answer_c' => '<p>tan(α) > 0; cot(α) < 0;</p>',
                'answer_d' => '<p>tan(α) < 0; cot(α) > 0.</p>',
                'image' => NULL,
                'explain' => '<p>Vì 0° < α < 90° (Góc phần tư thứ 1) nên tan(α) > 0; cot(α) > 0.</p>',
                'level' => 2,
                'teacher_id' => 4,
                'subject_id' => 1,
                'shared' => 1,
            ],
            [
                'question' => '<p>Giá trị của cot1485° là:</p>',
                'correct_answer' => '1',
                'answer_a' => '<p>1</p>',
                'answer_b' => '<p>-1</p>',
                'answer_c' => '<p>0</p>',
                'answer_d' => '<p>Không xác định</p>',
                'image' => NULL,
                'explain' => '<p>Ta có: cot1485° = cot(45° + 4.360°) = cot45° = 1.</p>',
                'level' => 2,
                'teacher_id' => 4,
                'subject_id' => 1,
                'shared' => 1,
            ],
            [
                'question' => '<p>Giá trị D = tan1°.tan2°…tan890.cot89°…cot2°.cot1° bằng:</p>',
                'correct_answer' => '2',
                'answer_a' => '<p>2</p>',
                'answer_b' => '<p>1</p>',
                'answer_c' => '<p>0</p>',
                'answer_d' => '<p>4</p>',
                'image' => NULL,
                'explain' => '<p>Ta có: tanα.cotα = 1 nên:<br>D = tan1°.tan2°…tan890.cot89°…cot2°.cot1°<br>= (tan1°.cot1°).(tan2°.cot2°)…(tan890.cot89°)<br>= 1.1…1<br>= 1.</p>',
                'level' => 3,
                'teacher_id' => 3,
                'subject_id' => 1,
                'shared' => 1,
            ],
            [
                'question' => '<p>Biểu thức A = cos2α.cot2α + 3cos2α – cot2α + 2sin2 α bằng.</p>',
                'correct_answer' => '3',
                'answer_a' => '<p>1</p>',
                'answer_b' => '<p>-1</p>',
                'answer_c' => '<p>2</p>',
                'answer_d' => '<p>-2</p>',
                'image' => NULL,
                'explain' => NULL,
                'level' => 3,
                'teacher_id' => 3,
                'subject_id' => 1,
                'shared' => 1,
            ],
            [
                'question' => '<p>Tam giác ABC có A = 120° khẳng định nào sau đây đúng?</p>',
                'correct_answer' => '2',
                'answer_a' => '<p>a<sup>2</sup> = b<sup>2</sup> + c<sup>2</sup> – 3bc;</p>',
                'answer_b' => '<p>a<sup>2</sup> = b<sup>2</sup> + c<sup>2</sup> + bc;</p>',
                'answer_c' => '<p>a<sup>2</sup> = b<sup>2</sup> + c<sup>2</sup> + 3bc;</p>',
                'answer_d' => '<p>a<sup>2</sup> = b<sup>2</sup> + c<sup>2</sup> – bc.</p>',
                'image' => NULL,
                'explain' => '<p>Áp dụng định lí Côsin tại đỉnh A ta có: a<sup>2</sup> = b<sup>2</sup> + c<sup>2</sup> – 2bc.cosA<br>⇒ a<sup>2</sup> = b<sup>2</sup> + c<sup>2</sup> – 2bc.cos120° = b<sup>2</sup> + c<sup>2</sup> + bc</p>',
                'level' => 2,
                'teacher_id' => 3,
                'subject_id' => 1,
                'shared' => 1,
            ],
            [
                'question' => '<p>Tính diện tích tam giác ABC biết A = 60°; b = 10; c = 20.</p>',
                'correct_answer' => '1',
                'answer_a' => '<p>50√3;</p>',
                'answer_b' => '<p>50√2;</p>',
                'answer_c' => '<p>50√5;</p>',
                'answer_d' => '<p>50.</p>',
                'image' => NULL,
                'explain' => NULL,
                'level' => 2,
                'teacher_id' => 1,
                'subject_id' => 1,
                'shared' => 0,
            ],
            [
                'question' => '<p>Tam giác ABC vuông tại A có AB = 6 cm; BC = 10 cm. Đường tròn nội tiếp tam giác đó có bán kính r bằng</p>',
                'correct_answer' => '2',
                'answer_a' => '<p>1cm</p>',
                'answer_b' => '<p>2cm</p>',
                'answer_c' => '<p>3cm</p>',
                'answer_d' => '<p>4cm</p>',
                'image' => NULL,
                'explain' => NULL,
                'level' => 2,
                'teacher_id' => 1,
                'subject_id' => 1,
                'shared' => 0,
            ],
            [
                'question' => '<p>Tính góc C của tam giác ABC biết a ≠ b và a(a<sub>2</sub> – c<sub>) = b(b<sub> – c<sub>).</p>',
                'correct_answer' => '2',
                'answer_a' => '<p>C = 150°</p>',
                'answer_b' => '<p>C = 120°</p>',
                'answer_c' => '<p>C = 60°</p>',
                'answer_d' => '<p>C = 30°</p>',
                'image' => NULL,
                'explain' => NULL,
                'level' => 2,
                'teacher_id' => 1,
                'subject_id' => 1,
                'shared' => 1,
            ],
            [
                'question' => '<p>Giả sử biết số đúng là 8217,3. Sai số tuyệt đối khi quy tròn số này đến hàng trục là</p>',
                'correct_answer' => '4',
                'answer_a' => '<p>7.3</p>',
                'answer_b' => '<p>2.3</p>',
                'answer_c' => '<p>0.3</p>',
                'answer_d' => '<p>2.7</p>',
                'image' => NULL,
                'explain' => '<p>Chữ số sau hàng làm tròn là 7 > 5 nên ta cộng thêm 1 đơn vị vào chữ số hàng làm tròn ta được số quy tròn là 8220<br>Khi đó sai số tuyệt đối là ∆ = |8220 – 8217,3| = 2,7.</p>',
                'level' => 1,
                'teacher_id' => 1,
                'subject_id' => 1,
                'shared' => 1,
            ],
        ]);
    }
}
