<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RoomRegistrationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now = Carbon::now();
        $lastWeek = $now->addDay(7);
        $monday = $lastWeek->startOfWeek()->format('Y-m-d');
        $tuesday = $lastWeek->startOfWeek()->addDays(1)->format('Y-m-d');
        $wednesday = $lastWeek->startOfWeek()->addDays(2)->format('Y-m-d');
        $dateTime = Carbon::now()->format('Y-m-d H:i:s');

        DB::table('room_registrations')->insert([
            [
                'purpose' => 'Dạy môn Toán lớp 10A1',
                'date' => $monday,
                'teacher_id' => 1,
                'start_time' => '07:00:00',
                'end_time' => '08:30:00',
                'amount' => 30,
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'purpose' => 'Dạy môn Toán lớp 10A2',
                'date' => $monday,
                'teacher_id' => 2,
                'start_time' => '07:00:00',
                'end_time' => '09:35:00',
                'amount' => 30,
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'purpose' => 'Dạy môn Toán lớp 10A3',
                'date' => $monday,
                'teacher_id' => 3,
                'start_time' => '09:35:00',
                'end_time' => '10:50:00',
                'amount' => 35,
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'purpose' => 'Dạy môn Toán lớp 10A4',
                'date' => $monday,
                'teacher_id' => 1,
                'start_time' => '09:35:00',
                'end_time' => '11:30:00',
                'amount' => 25,
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'purpose' => 'Dạy môn Toán lớp 10A5',
                'date' => $monday,
                'teacher_id' => 2,
                'start_time' => '10:30:00',
                'end_time' => '11:30:00',
                'amount' => 24,
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'purpose' => 'Dạy môn Văn lớp 11A1',
                'date' => $monday,
                'teacher_id' => 7,
                'start_time' => '07:00:00',
                'end_time' => '10:30:00',
                'amount' => 20,
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'purpose' => 'Dạy môn Văn lớp 11A2',
                'date' => $monday,
                'teacher_id' => 6,
                'start_time' => '12:00:00',
                'end_time' => '16:00:00',
                'amount' => 20,
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'purpose' => 'Dạy môn Vật Lý lớp 11A3',
                'date' => $monday,
                'teacher_id' => 14,
                'start_time' => '15:50:00',
                'end_time' => '16:40:00',
                'amount' => 20,
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'purpose' => 'Dạy môn Vật Lý lớp 12A1',
                'date' => $monday,
                'teacher_id' => 15,
                'start_time' => '13:15:00',
                'end_time' => '14:50:00',
                'amount' => 30,
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'purpose' => 'Dạy môn Vật Lý lớp 10A4',
                'date' => $monday,
                'teacher_id' => 13,
                'start_time' => '15:00:00',
                'end_time' => '15:15:00',
                'amount' => 22,
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'purpose' => 'Họp Tổ Toán',
                'date' => $tuesday,
                'teacher_id' => 2,
                'start_time' => '8:00:00',
                'end_time' => '9:00:00',
                'amount' => 10,
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'purpose' => 'Dạy môn Anh Văn 12',
                'date' => $tuesday,
                'teacher_id' => 35,
                'start_time' => '8:00:00',
                'end_time' => '9:00:00',
                'amount' => 35,
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'purpose' => 'Dạy môn Anh Văn 11',
                'date' => $tuesday,
                'teacher_id' => 33,
                'start_time' => '7:00:00',
                'end_time' => '8:30:00',
                'amount' => 33,
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'purpose' => 'Dạy môn Lịch sử 11A1',
                'date' => $tuesday,
                'teacher_id' => 23,
                'start_time' => '9:00:00',
                'end_time' => '10:30:00',
                'amount' => 30,
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'purpose' => 'Họp Tổ Thể dục - Quốc phòng',
                'date' => $tuesday,
                'teacher_id' => 36,
                'start_time' => '7:00:00',
                'end_time' => '7:30:00',
                'amount' => 10,
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'purpose' => 'Ngày hội tư vấn tuyển sinh',
                'date' => $tuesday,
                'teacher_id' => 42,
                'start_time' => '7:00:00',
                'end_time' => '11:30:00',
                'amount' => 50,
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'purpose' => 'Dạy môn Toán 12',
                'date' => $tuesday,
                'teacher_id' => 12,
                'start_time' => '8:00:00',
                'end_time' => '10:00:00',
                'amount' => 30,
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'purpose' => 'Dạy môn Toán 12',
                'date' => $tuesday,
                'teacher_id' => 11,
                'start_time' => '8:00:00',
                'end_time' => '10:00:00',
                'amount' => 28,
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'purpose' => 'Họp chi đoàn trường',
                'date' => $tuesday,
                'teacher_id' => 19,
                'start_time' => '15:00:00',
                'end_time' => '16:30:00',
                'amount' => 25,
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'purpose' => 'Dạy môn Hóa học 10',
                'date' => $tuesday,
                'teacher_id' => 20,
                'start_time' => '13:00:00',
                'end_time' => '14:30:00',
                'amount' => 31,
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'purpose' => 'Kiểm tra Toán 12A2',
                'date' => $tuesday,
                'teacher_id' => 11,
                'start_time' => '13:00:00',
                'end_time' => '13:45:00',
                'amount' => 31,
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'purpose' => 'Ngày hội tư vấn tuyển sinh',
                'date' => $wednesday,
                'teacher_id' => 42,
                'start_time' => '13:00:00',
                'end_time' => '16:30:00',
                'amount' => 50,
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'purpose' => 'Dạy môn Sinh học 11A2',
                'date' => $wednesday,
                'teacher_id' => 30,
                'start_time' => '15:00:00',
                'end_time' => '16:30:00',
                'amount' => 35,
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'purpose' => 'Họp Tổ Sinh học',
                'date' => $wednesday,
                'teacher_id' => 30,
                'start_time' => '13:00:00',
                'end_time' => '13:30:00',
                'amount' => 15,
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'purpose' => 'Dạy môn Toán 10',
                'date' => $wednesday,
                'teacher_id' => 2,
                'start_time' => '08:30:00',
                'end_time' => '11:00:00',
                'amount' => 30,
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
        ]);
    }
}
