<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class TeacherSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $dateTime = Carbon::now()->format('Y-m-d H:i:s');

        DB::table('teachers')->insert([
            [
                'username' => 'TC0001',
                'name' => 'Nguyễn Thị Mỹ Linh',
                'department_id' => 1,
                'gender' => 1,
                'date_of_birth' => '1970-12-02',
                'address' => 'Long An',
                'phone' => '0771234567',
                'email' => 'linhntm@gmail.com',
                'password' => Hash::make('12345678'),
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'username' => 'TC0002',
                'name' => 'Nguyễn Thanh Huy',
                'department_id' => 1,
                'gender' => 0,
                'date_of_birth' => '1989-04-21',
                'address' => 'Cần Thơ',
                'phone' => '0791234567',
                'email' => 'huynt@gmail.com',
                'password' => Hash::make('12345678'),
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'username' => 'TC0003',
                'name' => 'Nguyễn Thành Long',
                'department_id' => 1,
                'gender' => 0,
                'date_of_birth' => '1995-01-12',
                'address' => 'Cần Thơ',
                'phone' => '0796434567',
                'email' => 'longnt@gmail.com',
                'password' => Hash::make('12345678'),
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'username' => 'TC0004',
                'name' => 'Lê Thị Thúy Vy',
                'department_id' => 1,
                'gender' => 1,
                'date_of_birth' => '1997-12-24',
                'address' => 'Cần Thơ',
                'phone' => '0796434209',
                'email' => 'vyltt@gmail.com',
                'password' => Hash::make('12345678'),
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'username' => 'TC0005',
                'name' => 'Nguyễn Duy Quang',
                'department_id' => 2,
                'gender' => 0,
                'date_of_birth' => '1986-04-20',
                'address' => 'Cần Thơ',
                'phone' => '0796434341',
                'email' => 'quangnd@gmail.com',
                'password' => Hash::make('12345678'),
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'username' => 'TC0006',
                'name' => 'Lâm Thị Kim Thi',
                'department_id' => 2,
                'gender' => 1,
                'date_of_birth' => '1978-07-30',
                'address' => 'Đồng Nai',
                'phone' => '0796434450',
                'email' => 'chiltk@gmail.com',
                'password' => Hash::make('12345678'),
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'username' => 'TC0007',
                'name' => 'Nguyễn Thị Mỹ Duyên',
                'department_id' => 2,
                'gender' => 1,
                'date_of_birth' => '1990-04-24',
                'address' => 'Vĩnh Long',
                'phone' => '0791204450',
                'email' => 'duyenntm@gmail.com',
                'password' => Hash::make('12345678'),
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'username' => 'TC0008',
                'name' => 'Lê Như Quỳnh',
                'department_id' => 2,
                'gender' => 1,
                'date_of_birth' => '1984-12-06',
                'address' => 'Cần Thơ',
                'phone' => '0791784450',
                'email' => 'quynhln@gmail.com',
                'password' => Hash::make('12345678'),
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'username' => 'TC0009',
                'name' => 'Nguyễn Hà Tú Anh',
                'department_id' => 2,
                'gender' => 1,
                'date_of_birth' => '1990-10-12',
                'address' => 'Cần Thơ',
                'phone' => '0791781090',
                'email' => 'anhnht@gmail.com',
                'password' => Hash::make('12345678'),
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'username' => 'TC0010',
                'name' => 'Nguyễn Anh Thư',
                'department_id' => 2,
                'gender' => 1,
                'date_of_birth' => '1990-04-09',
                'address' => 'Cần Thơ',
                'phone' => '0791781054',
                'email' => 'thuna@gmail.com',
                'password' => Hash::make('12345678'),
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'username' => 'TC0011',
                'name' => 'Nguyễn Trí Bảo',
                'department_id' => 1,
                'gender' => 0,
                'date_of_birth' => '1990-11-07',
                'address' => 'Cần Thơ',
                'phone' => '0791771454',
                'email' => 'baont@gmail.com',
                'password' => Hash::make('12345678'),
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'username' => 'TC0012',
                'name' => 'Nguyễn Việt Tiến',
                'department_id' => 1,
                'gender' => 0,
                'date_of_birth' => '1990-10-22',
                'address' => 'Cần Thơ',
                'phone' => '0792951454',
                'email' => 'tiennv@gmail.com',
                'password' => Hash::make('12345678'),
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'username' => 'TC0013',
                'name' => 'Nguyễn Anh Quân',
                'department_id' => 3,
                'gender' => 0,
                'date_of_birth' => '1987-03-20',
                'address' => 'Cần Thơ',
                'phone' => '0798720454',
                'email' => 'quanna@gmail.com',
                'password' => Hash::make('12345678'),
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'username' => 'TC0014',
                'name' => 'Nguyễn Việt Hoàng',
                'department_id' => 3,
                'gender' => 0,
                'date_of_birth' => '1989-02-07',
                'address' => 'Cần Thơ',
                'phone' => '0798780454',
                'email' => 'hoangnv@gmail.com',
                'password' => Hash::make('12345678'),
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'username' => 'TC0015',
                'name' => 'Trần Anh Duy',
                'department_id' => 3,
                'gender' => 0,
                'date_of_birth' => '1990-04-12',
                'address' => 'Cần Thơ',
                'phone' => '0799078454',
                'email' => 'duyta@gmail.com',
                'password' => Hash::make('12345678'),
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'username' => 'TC0016',
                'name' => 'Nguyễn Thị Đan Thanh',
                'department_id' => 3,
                'gender' => 1,
                'date_of_birth' => '1990-09-22',
                'address' => 'Cần Thơ',
                'phone' => '0798038454',
                'email' => 'thanhntd@gmail.com',
                'password' => Hash::make('12345678'),
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'username' => 'TC0017',
                'name' => 'Võ Xuân Trúc',
                'department_id' => 3,
                'gender' => 1,
                'date_of_birth' => '1995-12-28',
                'address' => 'Cần Thơ',
                'phone' => '0793478454',
                'email' => 'trucvx@gmail.com',
                'password' => Hash::make('12345678'),
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'username' => 'TC0018',
                'name' => 'Trần Gia Hưng',
                'department_id' => 4,
                'gender' => 0,
                'date_of_birth' => '1999-10-02',
                'address' => 'Cà Mau',
                'phone' => '0791579454',
                'email' => 'hungtg@gmail.com',
                'password' => Hash::make('12345678'),
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'username' => 'TC0019',
                'name' => 'Võ Nguyễn Hoài Nam',
                'department_id' => 4,
                'gender' => 0,
                'date_of_birth' => '1999-07-23',
                'address' => 'Cà Mau',
                'phone' => '0790900454',
                'email' => 'namvnh@gmail.com',
                'password' => Hash::make('12345678'),
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'username' => 'TC0020',
                'name' => 'Trần Thị Thanh Tuyền',
                'department_id' => 4,
                'gender' => 1,
                'date_of_birth' => '1994-09-12',
                'address' => 'Cần Thơ',
                'phone' => '0799800454',
                'email' => 'tuyenttt@gmail.com',
                'password' => Hash::make('12345678'),
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'username' => 'TC0021',
                'name' => 'Nguyễn Văn Sáu',
                'department_id' => 4,
                'gender' => 0,
                'date_of_birth' => '1982-12-12',
                'address' => 'Cần Thơ',
                'phone' => '0793596454',
                'email' => 'saunv@gmail.com',
                'password' => Hash::make('12345678'),
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'username' => 'TC0022',
                'name' => 'Nguyễn Văn Thảo',
                'department_id' => 4,
                'gender' => 0,
                'date_of_birth' => '1984-08-10',
                'address' => 'Cần Thơ',
                'phone' => '0793093254',
                'email' => 'thaonv@gmail.com',
                'password' => Hash::make('12345678'),
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'username' => 'TC0023',
                'name' => 'Nguyễn Văn Chính',
                'department_id' => 5,
                'gender' => 0,
                'date_of_birth' => '1982-07-15',
                'address' => 'Cần Thơ',
                'phone' => '0793078304',
                'email' => 'chinhnv@gmail.com',
                'password' => Hash::make('12345678'),
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'username' => 'TC0024',
                'name' => 'Lê Thùy Linh',
                'department_id' => 5,
                'gender' => 1,
                'date_of_birth' => '1998-12-07',
                'address' => 'Cần Thơ',
                'phone' => '0793008214',
                'email' => 'linhlt@gmail.com',
                'password' => Hash::make('12345678'),
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'username' => 'TC0025',
                'name' => 'Phan Thị Diệu Hiền',
                'department_id' => 5,
                'gender' => 1,
                'date_of_birth' => '1999-06-12',
                'address' => 'Vĩnh Long',
                'phone' => '0790907214',
                'email' => 'hienptd@gmail.com',
                'password' => Hash::make('12345678'),
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'username' => 'TC0026',
                'name' => 'Nguyễn Thị Minh',
                'department_id' => 6,
                'gender' => 1,
                'date_of_birth' => '1986-05-15',
                'address' => 'Cần Thơ',
                'phone' => '0790045614',
                'email' => 'minhnt@gmail.com',
                'password' => Hash::make('12345678'),
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'username' => 'TC0027',
                'name' => 'Phạm Hồng Ngọc',
                'department_id' => 6,
                'gender' => 1,
                'date_of_birth' => '1998-01-23',
                'address' => 'Cần Thơ',
                'phone' => '0799000614',
                'email' => 'ngocph@gmail.com',
                'password' => Hash::make('12345678'),
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'username' => 'TC0028',
                'name' => 'Phạm Thị Hồng Thủy',
                'department_id' => 6,
                'gender' => 1,
                'date_of_birth' => '1987-01-31',
                'address' => 'Cần Thơ',
                'phone' => '0799128714',
                'email' => 'thuypth@gmail.com',
                'password' => Hash::make('12345678'),
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'username' => 'TC0029',
                'name' => 'Nguyễn Trần Trung Tín',
                'department_id' => 7,
                'gender' => 0,
                'date_of_birth' => '1989-10-26',
                'address' => 'Cần Thơ',
                'phone' => '0790451714',
                'email' => 'tinntt@gmail.com',
                'password' => Hash::make('12345678'),
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'username' => 'TC0030',
                'name' => 'Nguyễn Thị Kim Thúy',
                'department_id' => 7,
                'gender' => 1,
                'date_of_birth' => '1988-12-16',
                'address' => 'Cần Thơ',
                'phone' => '0770951714',
                'email' => 'thuyntk@gmail.com',
                'password' => Hash::make('12345678'),
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'username' => 'TC0031',
                'name' => 'Hoàng Quốc Việt',
                'department_id' => 7,
                'gender' => 0,
                'date_of_birth' => '1993-03-05',
                'address' => 'Cần Thơ',
                'phone' => '0773451714',
                'email' => 'viethq@gmail.com',
                'password' => Hash::make('12345678'),
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'username' => 'TC0032',
                'name' => 'Kiều Tố Linh',
                'department_id' => 8,
                'gender' => 1,
                'date_of_birth' => '1999-06-12',
                'address' => 'Đồng Tháp',
                'phone' => '0774891714',
                'email' => 'linhkt@gmail.com',
                'password' => Hash::make('12345678'),
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'username' => 'TC0033',
                'name' => 'Nguyễn Hoàng Đông',
                'department_id' => 8,
                'gender' => 0,
                'date_of_birth' => '1997-12-30',
                'address' => 'Kiên Giang',
                'phone' => '0799151171',
                'email' => 'dongnh@gmail.com',
                'password' => Hash::make('12345678'),
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'username' => 'TC0034',
                'name' => 'Võ Hoàng Yến',
                'department_id' => 8,
                'gender' => 1,
                'date_of_birth' => '1990-07-14',
                'address' => 'Cần Thơ',
                'phone' => '0771209314',
                'email' => 'yenvh@gmail.com',
                'password' => Hash::make('12345678'),
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'username' => 'TC0035',
                'name' => 'Phan Huỳnh Anh',
                'department_id' => 8,
                'gender' => 1,
                'date_of_birth' => '1999-02-22',
                'address' => 'Cần Thơ',
                'phone' => '0771026314',
                'email' => 'anhph@gmail.com',
                'password' => Hash::make('12345678'),
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'username' => 'TC0036',
                'name' => 'Trần Bá Dương',
                'department_id' => 9,
                'gender' => 0,
                'date_of_birth' => '1988-03-31',
                'address' => 'Cần Thơ',
                'phone' => '0770385314',
                'email' => 'duongtb@gmail.com',
                'password' => Hash::make('12345678'),
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'username' => 'TC0037',
                'name' => 'Lê Văn Xuân',
                'department_id' => 9,
                'gender' => 0,
                'date_of_birth' => '1994-07-30',
                'address' => 'Cần Thơ',
                'phone' => '0792895314',
                'email' => 'xuanlv@gmail.com',
                'password' => Hash::make('12345678'),
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'username' => 'TC0038',
                'name' => 'Trần Thanh Tân',
                'department_id' => 9,
                'gender' => 0,
                'date_of_birth' => '1992-02-12',
                'address' => 'Cần Thơ',
                'phone' => '0792091844',
                'email' => 'tantv@gmail.com',
                'password' => Hash::make('12345678'),
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'username' => 'TC0039',
                'name' => 'Nguyễn Quốc Mạnh',
                'department_id' => 9,
                'gender' => 0,
                'date_of_birth' => '1990-12-17',
                'address' => 'Cần Thơ',
                'phone' => '0792018644',
                'email' => 'manhnq@gmail.com',
                'password' => Hash::make('12345678'),
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'username' => 'TC0039',
                'name' => 'Võ Nguyễn Trường An',
                'department_id' => 10,
                'gender' => 0,
                'date_of_birth' => '1998-10-21',
                'address' => 'Cần Thơ',
                'phone' => '0792018105',
                'email' => 'anvnt@gmail.com',
                'password' => Hash::make('12345678'),
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'username' => 'TC0040',
                'name' => 'Nguyễn Hồ Hải Đăng',
                'department_id' => 10,
                'gender' => 0,
                'date_of_birth' => '1999-12-01',
                'address' => 'Bạc Liêu',
                'phone' => '0790610105',
                'email' => 'dangnhh@gmail.com',
                'password' => Hash::make('12345678'),
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
            [
                'username' => 'TC0041',
                'name' => 'Lê Ngọc Trúc',
                'department_id' => 11,
                'gender' => 1,
                'date_of_birth' => '1995-01-01',
                'address' => 'Cần Thơ',
                'phone' => '0790610672',
                'email' => 'trucln@gmail.com',
                'password' => Hash::make('12345678'),
                'created_at' => $dateTime,
                'updated_at' => $dateTime,
            ],
        ]);
    }
}
